### ISSUE TITLE
Weekly meeting for 2022-05-02 to 2022-05-24

### ISSUE THREAD

**Issue by denizeu** [Klepac-Ceraj-Lab/snakemake_workflows#40]
### What I accomplished last week

N/A

### What I plan to do next week

- [x] Accept invite to lab github org
- [x] Schedule ongoing meetings with Kevin / Anika for the summer
- [x] Keep Kevin posted via slack if I run into any trouble
- [x] MetaPhlAn tutorial: https://github.com/biobakery/biobakery/wiki/metaphlan3
- [x] Took notes on key terms: input, output, &visualization, as well as how these are used
- [x] Downloaded files to metaphlan_analysis directory
- [x] Took notes at the steps to make the directory/download the files to directory
- [x] Stuck at running single sample steps due to installation of metaphlan:
- [x] Currently trying to figure out how to install metaphlan: I downloaded minoconda: ''' curl -O https://repo.anaconda.com/miniconda/Miniconda3-py38_4.11.0-MacOSX-arm64.sh 
Current error: ‘PackagesNotFoundError: The following packages are not available from current channels
                 - python=3.7’ ''
- [x] HUMAnN tutorial: https://github.com/biobakery/biobakery/wiki/humann3
- [x] Review introduction to the method
- [x] Wasn’t able to get the correct conda download, will be able to do this once I have the correct programs 
- [x] contact Kevin about conda installation issues
- [x] Read eLife paper

### How did the last week go?

- [X] I accomplished all or most of my goals
- [ ] I used my time wisely
- [ ] I struggled with a problem, but solved it
- [X] I ran into an issue I can't solve on my own

**Comment by kescobo** [comment]
Make sure that any unfinished TODOs get added to the project tracker, or else are carried forward to the next week before closing this issue.

**Comment by kescobo** [comment]
Move any remaining todos to the project tracker or to next week's issue, then close this please :-)
